### ISSUE TITLE
Simulator simulates projectiles inheriting the player's velocity when they actually don't ingame

### ISSUE THREAD

**Issue by Sea-Kerman** [sebastianrasor/robinhood#1]
I'm strafing right. The simulator thinks the snowball will land at the red circle (as if it inherits the player's velocity) but it actually lands at the green circle
![2022-09-08_21 28 35](https://user-images.githubusercontent.com/41390862/189272281-d1a33eb3-6e86-43c8-b9a2-27074b25ebe5.png)

**Comment by sebastianrasor** [comment]
I've fixed this in an update that I'm currently working on, should be out soon (probably tonight but if not within a day or two.)

**Comment by Sea-Kerman** [comment]
nice
also is it possible to change the line color and thickness?

**Comment by sebastianrasor** [comment]
I've been trying to modify thickness but the renderer seems to ignore whatever thickness value I give it. I'll get offhand items working though

**Comment by Sea-Kerman** [comment]
haha, hacky terrible fix to the line thickness problem: draw more line and fuzz it 
![image](https://user-images.githubusercontent.com/41390862/189277328-b833bf75-27ca-4770-9e30-78300b8b397a.png)
![2022-09-08_22 21 52](https://user-images.githubusercontent.com/41390862/189277384-b2612b18-64d7-4be8-8eaa-908ebdbe1fae.png)

**Comment by sebastianrasor** [comment]
This is fixed in 1c5c3f03db981349ed34a80a9db3a87b2f8ea3c4

I will address the line width and offhand items soon.
