### ISSUE TITLE
Something in the 1.2.2 release makes it invisible with shaders

### ISSUE THREAD

**Issue by Sea-Kerman** [sebastianrasor/robinhood#2]
the 1.1.0 version works though

Fiddling around, hardcoding the linecolor to  fixes it for some reason

**Comment by Sea-Kerman** [comment]
I found a fix: 
![image](https://user-images.githubusercontent.com/41390862/189549336-7f9fe3ea-005b-4415-8414-1e5005375785.png)

**Comment by sebastianrasor** [comment]
Well that's a shame, I made the conscious decision to not allow alpha because I felt like the format of hex RGBA was too obscure and would just further complicate trying to change the color. It doesn't help that cloth config doesn't have an actual color picker.

**Comment by sebastianrasor** [comment]
should be fixed in b961fbd5b8ea6585fc961f1b961fe2659e086f92
